# train_csv: /path/to/train.csv                                #注释 原路径 2025.8.16
# train_img_path: /path/to/train_image                         #注释 原路径 2025.8.16
# val_csv: /path/to/val.csv                                    #注释 原路径 2025.8.16
# val_img_path: /path/to/val_image                             #注释 原路径 2025.8.16 
train_csv: /root/autodl-tmp/free_avatar/datasets01/FEC Google/train.csv                               #添加 服务器新路径 2025.8.24
train_img_path: /root/autodl-tmp/free_avatar/datasets01/FEC Google/train                              #添加 服务器新路径 2025.8.24
val_csv: /root/autodl-tmp/free_avatar/datasets01/FEC Google/val.csv                                   #添加 服务器新路径 2025.8.24
val_img_path: /root/autodl-tmp/free_avatar/datasets01/FEC Google/test                                 #添加 服务器新路径 2025.8.24

# train_csv: F:/code/code-replication1/free_avatar/datasets01/FEC Google/train.csv                   #添加 本地新路径 2025.8.23
# train_img_path: F:/code/code-replication1/free_avatar/datasets01/FEC Google/train                  #添加 本地新路径 2025.8.23
# val_csv: F:/code/code-replication1/free_avatar/datasets01/FEC Google/val.csv                       #添加 本地新路径 2025.8.23
# val_img_path: F:/code/code-replication1/free_avatar/datasets01/FEC Google/test                     #添加 本地新路径 2025.8.23
# 运行exp_emb_code\utils\convert_excel_to_csv.py    将.xlsx转为csv                                     #添加 注释 2025.8.21
# 运行exp_emb_code\utils\FEC_dataset_downloader.py  将FEC数据集图片裁剪下载                             #添加 注释 2025.8.21

# 本地/服务器切换                                                                                      #添加 修改注释 2025.8.24-
# 1.修改本文件train_csv、train_img_path、val_csv、val_img_path、mae_pretrain_checkpoints
# 2. 修改train.py文件arser.add_argument("--config", default="..省略...")                               #-添加 修改注释 2025.8.24
use_dp: False
device: [0]

# log_dir: "/root/autodl-tmp/free_avatar/exp_emb_code/log/vit_base_16_exp_emb"                          #修改第一次训练 原./log/vit_base_16_exp_emb 2025.8.24
# checkpoint_dir: "/root/autodl-tmp/free_avatar/exp_emb_code/checkpoints/vit_base_16_exp_emb"           #修改第一次训练 原./checkpoints/vit_base_16_exp_emb 2025.8.24

log_dir: "/root/autodl-tmp/free_avatar/exp_emb_code/log/vit_base_16_exp_emb_2025.8.24"                          #修改第二次训练 原./log/vit_base_16_exp_emb 2025.8.24
checkpoint_dir: "/root/autodl-tmp/free_avatar/exp_emb_code/checkpoints/vit_base_16_exp_emb_2025.8.24"           #修改第二次训练 原./checkpoints/vit_base_16_exp_emb 2025.8.24

print_freq: 20
accum_iter: 20                                                     # 修改第二次训练 原100 2025.8.24
batch_size: 64
num_workers: 8

num_epochs: 100
save_epoch: 1
# mae_pretrain_checkpoints: /path/to/pretrained_mae                                                                             #注释 原路径 2025.8.16
mae_pretrain_checkpoints: /root/autodl-tmp/free_avatar/datasets01/pretrained_mae/mae_pretrain_vit_base.pth                     #添加 服务器新路径 2025.8.24
# mae_pretrain_checkpoints: F:/code/code-replication1/free_avatar/datasets01/pretrained_mae/mae_pretrain_vit_base.pth         #添加 本地新路径 2025.8.21
resume: null

lr: 0.00005                                                         # 修改第二次训练 原0.002 2025.8.24
momentum: 0.9
weight_decay: 0.01                                                  # 修改第二次训练 原0.00005 2025.8.24
optim: "SGD"
